definitions:
  models.User:
    properties:
      birthday:
        type: string
      created_at:
        type: string
      deleted_at:
        type: integer
      email:
        type: string
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
    type: object
  models.UserCreated:
    properties:
      birthday:
        type: string
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create User
      operationId: create_user
      parameters:
      - description: UserRequest
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCreated'
      produces:
      - application/json
      responses:
        "201":
          description: User data
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Create User
      tags:
      - User
  /user/{id}:
    get:
      consumes:
      - application/json
      description: GEt User
      operationId: get_user
      parameters:
      - description: id
        in: path
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Get User
      tags:
      - Users
swagger: "2.0"
