// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/coffee": {
            "post": {
                "description": "Buy Coffee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coffee"
                ],
                "summary": "Buy Coffee",
                "operationId": "buy_coffee",
                "parameters": [
                    {
                        "description": "Coffee body",
                        "name": "coffee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/coffee.BuyCoffee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coffee data",
                        "schema": {
                            "$ref": "#/definitions/coffee.PreparedCoffee"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/courier": {
            "post": {
                "description": "Buy Deliver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliver"
                ],
                "summary": "Buy Deliver",
                "operationId": "deliver",
                "parameters": [
                    {
                        "description": "Coffee body",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/courier.TakeOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coffee data",
                        "schema": {
                            "$ref": "#/definitions/courier.DeliverOrder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "coffee.BuyCoffee": {
            "type": "object",
            "properties": {
                "is_paid": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "coffee.PreparedCoffee": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "courier.DeliverOrder": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/courier.Product"
                    }
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "courier.Product": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "courier.TakeOrder": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "is_paid": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
