definitions:
  coffee.BuyCoffee:
    properties:
      is_paid:
        type: boolean
      name:
        type: string
    type: object
  coffee.PreparedCoffee:
    properties:
      name:
        type: string
      price:
        type: integer
      volume:
        type: integer
    type: object
  courier.DeliverOrder:
    properties:
      products:
        items:
          $ref: '#/definitions/courier.Product'
        type: array
      time:
        type: string
    type: object
  courier.Product:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  courier.TakeOrder:
    properties:
      address:
        type: string
      is_paid:
        type: boolean
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /coffee:
    post:
      consumes:
      - application/json
      description: Buy Coffee
      operationId: buy_coffee
      parameters:
      - description: Coffee body
        in: body
        name: coffee
        required: true
        schema:
          $ref: '#/definitions/coffee.BuyCoffee'
      produces:
      - application/json
      responses:
        "200":
          description: Coffee data
          schema:
            $ref: '#/definitions/coffee.PreparedCoffee'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Buy Coffee
      tags:
      - Coffee
  /courier:
    post:
      consumes:
      - application/json
      description: Buy Deliver
      operationId: deliver
      parameters:
      - description: Coffee body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/courier.TakeOrder'
      produces:
      - application/json
      responses:
        "200":
          description: Coffee data
          schema:
            $ref: '#/definitions/courier.DeliverOrder'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Buy Deliver
      tags:
      - Deliver
swagger: "2.0"
